name: nyc_mobility_dbt
version: "1.0.0"
config-version: 2

# dbt Cloud ignores this. dbt Core in VS Code looks for a profile with this name in
# ~/.dbt/profiles.yml. Same name as the green taxi project.
profile: nyc_mobility_dbt

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: target
clean-targets: ["target", "dbt_packages"]

models:
  nyc_mobility_dbt:
    +materialized: view
    staging:
      +materialized: view
    clean:
      +materialized: incremental
